Don't scale labels by default
ome/omero-iviewer pull request #443
Opened 2023-01-13 11:15 UTC by will-moore

Fixes #442.

This changes the `scale` behaviour for labels and shape text.

I think the behaviour of NOT scaling labels as you zoom (typical behaviour on maps etc) is generally preferable.

But that would be a breaking change - E.g. in this case, all the labels are 200px high, and if shown that large at lower zoom levels then they would obscure the image (and each other): https://chamber.mrc.ox.ac.uk/iviewer/?images=124

So I guess we need this to be configurable (as suggested in issue above).

2023-02-03 16:54 UTC, pwalczysko commented
Trying to compare 
https://merge-ci.openmicroscopy.org/web/webclient/img_detail/211615/?dataset=50619
and
https://latest-ci.openmicroscopy.org/web/webclient/img_detail/85715/?dataset=43469

Not sure, maybe need an detailed explanation what is the difference in the two scalebar behaviours when zooming those images ?

2023-02-03 16:56 UTC, will-moore commented
Sorry, that last commit won't be deployed on merge-ci yet.
And this PR has nothing to do with scalebar.
It's about how text labels scale when you zoom an image.
Default behaviour is to zoom the text when you zoom. This PR and merge-ci is configured to disable that.

2023-02-06 14:33 UTC, pwalczysko commented
> Sorry, that last commit won't be deployed on merge-ci yet. And this PR has nothing to do with scalebar. It's about how text labels scale when you zoom an image. Default behaviour is to zoom the text when you zoom. This PR and merge-ci is configured to disable that.

Ah, sorrry, I can see it now. Yes, the text does not zoom on an image in merge-ci.

2023-02-06 14:52 UTC, pwalczysko commented
Problem:

1. Zoom out on an svs image to 30%. 
2. Draw a Text label which approx. as big as the size of the white area in the top-left corner of the screenshot below
3. Observe that once you have finished drawing, the label jumps in size to be more than twice as big as you intended

![Screenshot 2023-02-06 at 14 50 25](https://user-images.githubusercontent.com/2478303/217004081-d903cb9a-b07f-473f-9d24-17e9ae87f5c9.png)

2023-02-06 14:53 UTC, pwalczysko requested changes
Please address the drawing of new labels problem.

2023-05-03 14:43 UTC, will-moore commented
Couldn't find a fix for that problem despite a few different attempts.

2023-05-03 14:43 UTC, closed without merging